<a href="https://colab.research.google.com/github/rsubodha/machineLearning/blob/main/customerChurn.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
# prompt: import numpy, pandas, tensor flow

import numpy as np
import pandas as pd
import tensorflow as tf


In [ ]:
# prompt: tf version

tf.__version__


'2.15.0'

# Part 1 - Data Preprocessing

import the dataset

In [ ]:
# prompt: import the dataset Churn_Modelling.csv and import all the rows starting with column index 3 till -1 and assign it to a variable x, create another variable y and assign the dependent variable which is the last column

data = pd.read_csv('Churn_Modelling.csv')
x = data.iloc[:,3:-1].values
y = data.iloc[:, -1].values


In [ ]:
# prompt: print x and y from above

print(x)
print(y)


[[619 'France' 'Female' ... 1 1 101348.88]
 [608 'Spain' 'Female' ... 0 1 112542.58]
 [502 'France' 'Female' ... 1 0 113931.57]
 ...
 [709 'France' 'Female' ... 0 1 42085.58]
 [772 'Germany' 'Male' ... 1 0 92888.52]
 [792 'France' 'Female' ... 1 0 38190.78]]
[1 0 1 ... 1 1 0]


Encoding categorical data

In [ ]:
# prompt: create a label encoder function for the dataset for column index 2 and use "le" as variable name for label encoder

from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
x[:,2] = le.fit_transform(x[:,2])


In [ ]:
# prompt: print x

print(x)


[[619 'France' 0 ... 1 1 101348.88]
 [608 'Spain' 0 ... 0 1 112542.58]
 [502 'France' 0 ... 1 0 113931.57]
 ...
 [709 'France' 0 ... 0 1 42085.58]
 [772 'Germany' 1 ... 1 0 92888.52]
 [792 'France' 0 ... 1 0 38190.78]]


One hot encoding the "geography" column

In [ ]:
# prompt: create a one hot encoding column on column index 1

from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder

ct = ColumnTransformer([('encoder', OneHotEncoder(), [1])], remainder='passthrough')
x = np.array(ct.fit_transform(x))


In [ ]:
# prompt: pint x

print(x)


[[1.0 0.0 0.0 ... 1 1 101348.88]
 [0.0 0.0 1.0 ... 0 1 112542.58]
 [1.0 0.0 0.0 ... 1 0 113931.57]
 ...
 [1.0 0.0 0.0 ... 0 1 42085.58]
 [0.0 1.0 0.0 ... 1 0 92888.52]
 [1.0 0.0 0.0 ... 1 0 38190.78]]


Splitting the dataset to training and test

In [ ]:
# prompt: split the data set using 80 20 rule

from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size = 0.2, random_state = 0)


Feature scaling

In [ ]:
# prompt: from the above data set split, create feature scaling using standard scaler

from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
x_train = sc.fit_transform(x_train)
x_test = sc.transform(x_test)


# Part 2 - Build the ANN

Initialize ANN

In [ ]:
# prompt: initialise a variable called "ann" artificial neural network using keras

ann = tf.keras.models.Sequential()


Add input layer and first hidden layer

In [ ]:
# prompt: add a first hidden layer to above variable ann

ann.add(tf.keras.layers.Dense(units=6, activation='relu'))


Add second hidden layer

In [ ]:
# prompt: add another hidden layer to above the ann

ann.add(tf.keras.layers.Dense(units=6, activation='relu'))


Add output layer

In [ ]:
# prompt: add an output layer

ann.add(tf.keras.layers.Dense(units=1, activation='sigmoid'))


# Part 3 -Training the ANN

Compile

In [ ]:
# prompt: compile the Ann

ann.compile(optimizer = 'adam', loss = 'binary_crossentropy', metrics = ['accuracy'])


Training using training dataset

In [ ]:
# prompt: train the ann using batch size

ann.fit(x_train, y_train, batch_size=32, epochs=100)


Epoch 1/100
250/250 [==============================] - 2s 2ms/step - loss: 0.5577 - accuracy: 0.7240
Epoch 2/100
250/250 [==============================] - 0s 2ms/step - loss: 0.4621 - accuracy: 0.7996
Epoch 3/100
250/250 [==============================] - 0s 2ms/step - loss: 0.4324 - accuracy: 0.8106
Epoch 4/100
250/250 [==============================] - 0s 2ms/step - loss: 0.4121 - accuracy: 0.8224
Epoch 5/100
250/250 [==============================] - 0s 2ms/step - loss: 0.3978 - accuracy: 0.8309
Epoch 6/100
250/250 [==============================] - 0s 2ms/step - loss: 0.3871 - accuracy: 0.8364
Epoch 7/100
250/250 [==============================] - 0s 2ms/step - loss: 0.3795 - accuracy: 0.8366
Epoch 8/100
250/250 [==============================] - 0s 2ms/step - loss: 0.3742 - accuracy: 0.8410
Epoch 9/100
250/250 [==============================] - 0s 2ms/step - loss: 0.3704 - accuracy: 0.8436
Epoch 10/100
250/250 [==============================] - 0s 2ms/step - loss: 0.3673 - accura

# Part 4 - Making the predictions

Predicting the result of a single observation

In [ ]:
# prompt: predict based on observation of geography, credit score, gender, age, tenure, balance, number of products, does this customer have credit card, is this customer an active member, estimated salary the output should be  binary outcome

x_new = sc.transform([[1,0 ,0, 600, 1, 40, 3, 60000, 2, 1, 1, 50000]])
y_pred = ann.predict(x_new)
y_pred = (y_pred > 0.5)
print(y_pred)


1/1 [==============================] - 0s 20ms/step
[[False]]


Predicting the test results

In [ ]:
# prompt: predict using test data

y_pred = ann.predict(x_test)
y_pred = (y_pred > 0.5)
print(y_pred)


63/63 [==============================] - 0s 5ms/step
[[False]
 [False]
 [False]
 ...
 [False]
 [False]
 [False]]


Making the confusion matrix

In [ ]:
# prompt: determine the accuracy

from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_pred)
print(cm)

accuracy = (cm[0][0] + cm[1][1]) / (cm[0][0] + cm[0][1] + cm[1][0] + cm[1][1])
print('Accuracy:', accuracy)


[[1517   78]
 [ 198  207]]
Accuracy: 0.862
